import {HookPage} from "../../libs/mp";

HookPage({
  navTitle: 'rich-html',
  data: {


    html: `
    <p></p><p></p><p></p><p></p><p></p><p></p><div>
<div><div>
<div><b>一、包修期外(含包内因外力、使用不当、配件遗失等原因造成的维修)</b></div>
<div><b><br></b></div>
<p>1、服务收费项目（除小家电）：上门费、维修费、因需换件的可向顾客按《老板电器服务收费手册》收取配件费；超出服务范围的可收取远程费<br>2、服务收费项目（小家电）：维修费、因需换件的可向顾客按《老板电器服务收费手册》收取配件费；因顾客要求上门服务可收取上门费，超出服务范围的可收取远程费<br>注：</p>
<p>服务过程中，未换件、未拆机的只收取上门费，超出服务范围的可收取远程费<br></p><p><br></p>
</div></div>
<div><div>
<div><b>二、易损件上门服务</b></div>
<div><b><br></b></div>
<p>1、服务收费项目：因顾客要求上门可收取上门费、包外可向顾客按《老板电器服务收费手册》收取配件费；超出服务范围的可收取远程费<br>2、因维修产品而顺带易损配件的不可向用户收取上门费、远程费、维修费<br></p>
</div></div>
<div><div>
<div><b>三、包外配件收费服务后包修承诺</b></div>
<div><b><br></b></div>
<p>就更换过的配件凭服务单等有效凭证，自维修之日起可以包修三个月</p><p><br></p>
</div></div>
<div>
<div><b>四、小家电产品线</b></div>
<div>电压力煲、电磁炉、电热水壶、食品加工机、电饭煲<b><br></b>
</div>
<div><b><br></b></div>
<p><b>五、服务收费价目表</b><br></p>
<p><b><br></b></p>
</div>
<div>
<div><table style="background-color: rgb(255, 255, 255);">
<thead><tr>
<td>类别</td>
<td>上门费</td>
<td>远程费</td>
<td>检测</td>
<td>上门咨询</td>
<td>维修费</td>
<td>二次安装</td>
</tr></thead>
<tbody>
<tr>
<td>油烟机</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>30</td>
</tr>
<tr>
<td>灶具</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>消毒柜</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>微波炉</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>蒸汽炉</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>烤箱</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>暖碟机</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>20</td>
</tr>
<tr>
<td>洗碗机</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>40</td>
<td>50</td>
</tr>
<tr>
<td>净水机</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>60</td>
</tr>
<tr>
<td>前置过滤器</td>
<td>30</td>
<td>远程费标准</td>
<td>—</td>
<td>—</td>
<td>20</td>
<td>45</td>
</tr>
</tbody>
</table></div>
<p><br></p>
<p>远程费：一二级城市及总站范围远程费不超过50，三四级城市（不含总站）远程费不超过200，以上标准自2013年1月1日起开始执行<br></p><p><br></p>
</div>
<div><div>
<div><b>六、灶具改气源服务</b></div>
<div><b><br></b></div>
<table>
<thead><tr>
<td>气源更换方式</td>
<td>灶具类型</td>
<td>收费金额</td>
<td>备注</td>
</tr></thead>
<tbody>
<tr>
<td>
<p>天然气</p>
<p></p>
<p>液化气</p>
</td>
<td>单眼</td>
<td>50</td>
<td>指定区域外收取远程费</td>
</tr>
<tr>
<td>双眼</td>
<td>70</td>
</tr>
<tr>
<td>三眼</td>
<td>90</td>
</tr>
<tr>
<td>
<p>天然气，液化气</p>
<p>人工气</p>
</td>
<td>单眼</td>
<td rowspan="6">80</td>
</tr>
<tr>
<td>双眼</td>
<td>140</td>
</tr>
<tr>
<td>三眼</td>
<td>180</td>
</tr>
</tbody>
</table>
<p><br></p>
<p><br></p>
<p><b>注：</b></p>
<p>1、远程费标准：一二线城市及总站范围不超过50元，三四线城市（不含总站）不超过200元</p>
<p>2、改气源换下的配件，用户无需退回本公司</p>
</div></div>
</div><p><br></p>

<p></p><p></p><p></p><p></p><p></p><p></p><p></p><div id="js_title">
<p><span >厨房的装修是整个装修过程中非常重要的一部分，厨房吊顶建负责防油烟、防潮的“重任”。在装饰厨房吊顶时，选材至关重要，吊顶选材好厨房装修就成功了一大半，今天就和大家来分享下厨房厨房吊顶的选材攻略。</span></p>
<p></p>
<h3><span >1、 PVC</span></h3>
<p><span >PVC吊顶以PVC为原料，企口式型材加工而成为具有重量级、安装简便、防水、防潮的特点，多的表面花色图案变化，并且耐毁坏、好清晰、有隔音、隔热的良好性能、它本钱低、装饰效果好、因此成为厨房吊顶的主选材料。PVC的缺点是容易变黄，“处女座”朋友可能不适合选择它。</span></p>
</div><p><img src="http://img.zhuangzizai.com/details/201904/sDyIzAkYSiCWXvRsMsfZiXyk0j26nJQBnD3YO11D.jpeg" style="max-width: 100%;" class=""></p><h3><span md-inline="plain">2、 铝扣板</span></h3><p cid="n9" mdtype="paragraph"><span md-inline="plain">铝扣板是新型的吊顶材料、具有防火、防潮、防腐、抗静电、吸音、隔音的优点，其常用形状有长形、方形、表面有平面和冲孔两种，两者差别主要在硬度。微孔铝板又叫做暗骨方型扣板花吊顶系统，其板面平整、接缝细、设计简洁大方、微孔铝板的标准规格为：350x350mm、600x600mm、600x1200mm。铝扣板的检验主要看漆膜光泽的厚度。</span></p><p><span data-raw-text="。" data-textnode-index="6" data-index="402"><img src="http://img.zhuangzizai.com/details/201904/Xc22wOrWF3Bb0dpNDvWenYBFH9LDLZUw3PcPlu9d.jpeg" style="max-width:100%;"><br></span></p><h3><span md-inline="plain">3、 集成吊顶</span></h3><p cid="n14" mdtype="paragraph"></p><p cid="n15" mdtype="paragraph"><span md-inline="plain">集成吊顶（有称真题吊顶、组合吊顶、智能吊顶），是继整体浴室和整体厨房出现后，厨卫吊顶装饰的新产品，他代表着当今厨卫吊顶装饰对的技术。集成吊顶打破了原有传统吊顶的一成不变，真正将原有产品达到了模块化、组件化，让你在选择吊顶材料、换气照明及取暖模块效果一目了然。</span></p><p><span data-raw-text="。" data-textnode-index="8" data-index="538"><img src="http://img.zhuangzizai.com/details/201904/pu69CY7X57MBJEvB2brRzSKK1BCgNUn6gblpULr1.jpeg" style="max-width:100%;"><br></span></p><h3><span md-inline="plain">4、 石膏板</span></h3><p cid="n21" mdtype="paragraph"></p><p cid="n22" mdtype="paragraph"><span md-inline="plain">石膏板其实很少使用在厨房吊顶中，因为石膏板的核心成分是石膏，固防水性不好，在潮湿的环境中容易受潮编织。石膏板的装饰效果很好，延展性和造型能力很强，价格也比较实惠。如果能够确保厨房干燥，那么还是可以使用石膏板吊顶的。目前市场普通石膏板的常用规格有1200x3000mm和1200x2440mm两种，厚度一般为9mm。其特点是价格低，但是遇水遇潮容易软化或分解，厨房环境潮湿不建议使用。</span></p><p><span data-raw-text="。" data-textnode-index="10" data-index="735"><img src="http://img.zhuangzizai.com/details/201904/Xnhj9lei0GbfYgJ5E4kuWcOswJdur67HGlqNcuE3.jpeg" style="max-width:100%;"><br></span></p><h3><span md-inline="plain">5、 铝塑板</span></h3><p cid="n28" mdtype="paragraph"></p><p cid="n29" mdtype="paragraph"><span md-inline="plain">铝塑板作为一种新型装饰材料，仅仅数年间，便以其进经济性、可选色彩的多样性、便捷的施工方式、优良的加工性能、防火性以及高贵的品质，快速受到人们的青睐。铝塑板氛围单面和双面，由铝层与塑层组成，单面较柔软，双面较硬挺，家庭装修常用双面铝塑板。铝塑板常见规格为1220x2440，颜色丰富，是市内吊顶、包管的上好材料。很多高楼的外墙和门脸也都是这种材料。</span></p><p><span data-raw-text="。" data-textnode-index="13" data-index="915"><img src="http://img.zhuangzizai.com/details/201904/YZXvSHllgkV44vN6AtsHbvFLffO2VKR7uiroAtiZ.jpeg" style="max-width:100%;"><br></span></p><h3><span md-inline="plain">6、 矿棉板</span></h3><p cid="n36" mdtype="paragraph"></p><p cid="n37" mdtype="paragraph"><span md-inline="plain">矿棉板在厨房吊顶中使用最少，其核心成分是碳，质量很重，很坚固，所以价格也相对较高。石膏制品又是特级防火材料，在火焰中能产生吸热反应，同时，释放出水分子阻止火势蔓延，而且不会分解产生任何有毒的、侵蚀性的、令人窒息的气体，也不会产生任何助燃物或烟气。矿棉板的规格多为600x600mm，主要用于工作室，商场等场所，小户型家庭一般并不适用。</span></p><p><span data-raw-text="。" data-textnode-index="17" data-index="1091"><img src="http://img.zhuangzizai.com/details/201904/vct8IQh5uEPW1pULp5L7EPt4AHJs1V3I9QDLIPrc.jpeg" style="max-width:100%;"><br></span></p><p><span data-raw-text="。" data-textnode-index="17" data-index="1091">以上就是目前常见的6中厨房吊顶的材料分类，大家可以根据自己的需求进行选择判断。<br></span></p><p><br></p>
`
  }
});
